### ISSUE TITLE
Offset of jumps and branches are always the same for every tag

### ISSUE THREAD

**Issue by fernando-lahoz** [emilmasoumi/ebpf-assembler#1]
I've recently used this assembler as it is much handy for the use I do of it for BPF than using C macros, but I've seen that jumping instructions always use the same offset for each tag. Rather than the offset between caller and callee, tags seem to be translated to the index of the instruction they refer. Taking the example shown in README.txt:
```
  mov r1 64
  mov32 r2 32
  jlt r2 r1 end ; This is translated to jlt r2 r1 +8 instead of jlt r2 r1 +4
  jge r1 r2 end ; This is translated to jge r1 r2 +8 instead of jge r1 r2 +3
loop:
  sub r1 1
  add32 r2 1
  jle r1 r2 loop  ; This is translated to jle r1 r2 +5 instead jle r1 r2 -3
end:
  mov r0 0
  exit
```
LLVM backend calculates it as:  `offset := #dst - #jmp - 1`

**Comment by emilmasoumi** [comment]
Thanks for your feedback. The intended behavior by the kernel team may not have been clear at the time of implementing this code, but it is now evident from the documentation that the branching target offset must be relative to the branched instruction offset and not the absolute instruction offset.

It should now behave in accordance with the BPF standard.
